# Change these first
owner: xadi-hq
repo: emailconnect-status

sites:
  - name: emailconnect.eu
    url: https://emailconnect.eu
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  cname: status.emailconnect.eu
  favicon: https://emailconnect.eu/assets/favicon-DmDkn9pI.ico
  faviconSvg: https://emailconnect.eu/assets/images/favicon-DiWvSVNU.svg
  logoUrl: https://raw.githubusercontent.com/xadi-hq/emailconnect-status/master/assets/logo-light.png
  name: EmailConnect
  introTitle: "**EmailConnect** turns emails into webhooks, 100% EU operated."
  introMessage: This is a status page showing **real-time** up-time data from our infrastructure. [**Get started free**](https://emailconnect.eu/?ref=statuspage)
  metaTags:
    - name: "robots"
      content: "noindex"
  navbar:
    - title: Home
      href: https://emailconnect.eu/?ref=statuspage
    - title: Help center
      href: https://emailconnect.eu/help?ref=statuspage
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
